export { content, homeContent } from "../../apps/website/lib/site/home-content";
export type {
  LandingPageAudienceUseCase,
  LandingPageAudiences,
  LandingPageContent,
  LandingPageCta,
  LandingPageFaq,
  LandingPageFaqItem,
  LandingPageFinalCta,
  LandingPageHero,
  LandingPageIdea,
  LandingPageIdeaBlock,
  LandingPageMitwirkung,
  LandingPageMitwirkungPath,
  LandingPageProblem,
  LandingPageProblemScenario,
  LandingPageStatus,
  LandingPageStatusGroup,
  LandingPageStatusItem,
  LandingPageStatusTag,
  LandingPageStatusTone,
  LandingPageTrust,
  LandingPageTrustItem,
} from "../../apps/website/lib/site/home-content";
